<a href="https://colab.research.google.com/github/tderr24/MAT-422/blob/main/HW_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MAT 422

## HW 1.2 - Elements of Linear Algebra

### Thomas Derr

In [ ]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt

# 1.2.1 Linear Spaces


#### 1 Linear Combination


- linear combination - new vector constructed by multiplying two vectors and adding the result
- linear subspace - a subset $U \subseteq V$ that is closed under vector addition and multiplication
- column space - span of the columns of a given matrix
    - span = the set of all linear combinations of $w_i$ in a linear subspace

In [ ]:
vectorX = np.array([0, 1, 2, 3])
vectorY = np.array([4, 5, 6, 7])

LinearCombination = 5 * vectorX + 2 * vectorY

# Both vectorX and vectorY are in R^4

a = 3  # could be any real number
b = 2  # could be any real number

span = a * vectorX + b * vectorY
# the span of these two vectors is in R4


In this case, our resulting span is

[0, a, 2a, 3a] + [4b, 5b, 6b, 7b] which works out to all vectors of the form [4b, a + 5b, 2a + 6b, 3a + 7b] in $R^4$

When we use $a = 3, b=2$ we get the vector [8, 13, 18, 23] which is vector in the span of a and b which itself is a linear subspace of $R^4$

#### 2 Linear Independence and Dimension


- two vectors are linearly independent if no linear combination of them equals the zero vector (as long as not all $\sigma_i$ equals 0)
    - otherwise they are linearly dependent
- A basis for a vector space is a set of vectors that can create any element in the space through linear combinations.
    - There can be multiple bases for a vector space but they must all have the same dimension (number of elements)


In [ ]:
# Each axis in R3 is defined by a unique linearly independent vector

x = np.array([1, 0, 0])
y = np.array([0, 1, 0])
z = np.array([0, 0, 1])

# additionally with linear combinations of these three vectors, we can make any vector in R3

# thus these vectors also form a basis for the vector space R3


#Example if we wanted to make the point [4, 3 , 2], we can do it like this

fourThreeTwo = 4*x + 3*y + 2 * z
fourThreeTwo

array([4, 3, 2])

# 1.2.2 Orthogonality

#### 1 Orthonormal Bases

In the previous example, we established that x, y, and z formed a basis for $R^3$

Because they all happen to be unit vectors of length 1, and are orthogonal to eachother, they are also an orthonormal basis

#### 2 Best Approximation Theorem

- essentially allows us to find the closest vector in a subspace to some vector not in that subspace


A trivial example might be

In [ ]:
vectorR3 = [1, 2, 3]
bestApproxR2 = [1,2]

Perhaps we want to find the closest vector in $R^2$ to this vector in $R^3$

This is a bit over simplified but since $R^2$ is a subset of $R^3$ (any vector of the form [a,b] in  $R^2$ can be shown as [a, b, 0] in $R^3$) we essentially want to find a point in $R^2$ that we can draw a line to $R^3$ with the shortest possible distance (i.e. by creating a line orthogonal to $R^2$ in $R^3$ that passes through our point)

For this case, the vector [1,2] would be the best approximation of [1,2,3] in $R^2$


# 1.2.3 Gram-Schmidt Process


- Process used to determine an orthonormal basis of a span of vectors


In [ ]:
vectorA = np.array([4,1])

vectorB = np.array([2,3])


vA = vectorA #normalize

vB = vectorB - (np.dot(vectorA, vectorB) / np.dot(vectorA, vectorA)) * vectorA

vA, vB


(array([4, 1]), array([-0.58823529,  2.35294118]))

# 1.2.4 Eigenvalues and Eigenvectors

For any square matrix $A \in \mathbb{R} ^{d\times d}$

$\lambda$ is an eigenvalue if $A$ if there exists a nonzero vector x such that $Ax = \lambda x$

if such $x$ exists it is called an eigenvector

In [ ]:
vector = np.array([[4,1], [5, 2]])

vals, vecs = np.linalg.eig(vector)

In [ ]:
vals # eigenvalues

array([5.44948974, 0.55051026])

In [ ]:
vecs  # eigenvectors

array([[ 0.56786837, -0.27843404],
       [ 0.82311938,  0.96045535]])